
[package]
name = "RayTest"
version = "0.1.0"
edition = "2024"

[dependencies]

stl_io = "0.8.5"
nalgebra = "0.33.2"
image = "0.25.6"
derive_builder = "*"

# Tests
approx = "*"

# Info
indicatif = "*"

# GUI
#egui = "0.31"
#eframe = "0.31"
