[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
engine = { path = "../engine", version = "*" }
image = "*"

# Info
indicatif = "*"

# GUI
egui = "0.31"
eframe = "0.31"

cpu-time = "*"

rand_chacha = "0.9"
rand_xoshiro = "0.7.0"
rand_pcg = "0.9.0"
rand = "0.9.1"
